const ar = {
  //Book Details
  bookRemoved: "تم إزالة الكتاب من المفضلة",
  bookAdded: "تمت إضافة الكتاب إلى المفضلة",
  errorMessage: "حدث خطأ ما.",
  forSale: "للبيع",
  currentlyBorrowed: "الكتاب مُعار حالياً (يمكنك حجز فترة أخرى)",
  availableToBorrow: "متاح للاستعارة",
  availableToExchange: "متاح للتبادل",
  freeToDonate: "متاح للتبرع",
  bookNotFound: "الكتاب غير موجود أو غير متاح.",
  general: "عام",
  proceedToOrder: "إتمام الطلب",
  reportBook: "الإبلاغ عن هذا الكتاب",
  by: "بواسطة",
  unknownAuthor: "مؤلف غير معروف",
  listedBy: "مدرج بواسطة:",
  unknown: "غير معروف",
  home: "الرئيسية",
  category: "الفئة",
  currency: "جنيه",
  noReportsFound: "لا توجد تقارير",
  noReportsDescription:
    "لم تقم بإرسال أي تقارير بعد. استكشف الكتب وقم بالإبلاغ عن أي مشاكل تجدها.",
  browseBooks: "تصفح الكتب",
  status: "الحالة",
  targetType: "نوع الهدف",
  all: "الكل",
  pending: "قيد الانتظار",
  reviewed: "تم المراجعة",
  dismissed: "مرفوض",
  cancelled: "ملغى",
  user: "مستخدم",
  book: "كتاب",
  mySubmittedReports: "تقاريري المقدمة",
  showingResults: "عرض {start} إلى {end} من أصل {total} نتيجة",
  target: "الهدف",
  reason: "السبب",
  dateSubmitted: "تاريخ الإرسال",
  action: "إجراء",
  userNotFound: "المستخدم غير موجود",
  bookNotFound: "الكتاب غير موجود",
  confirmCancelReport: "تأكيد إلغاء التقرير",
  cancelReportConfirmation:
    "هل أنت متأكد أنك تريد إلغاء هذا التقرير؟ لا يمكن التراجع عن هذا الإجراء.",
  no: "لا",
  yesCancel: "نعم، إلغاء",
  cancel: "إلغاء",
  pending: "قيد الانتظار",
  reviewed: "تم المراجعة",
  dismissed: "مرفوض",
  cancelled: "ملغى",
  sendReport: "إرسال التقرير",
  sending: "جاري الإرسال...",
  reportBook: "الإبلاغ عن الكتاب",
  additionalComments: "تعليقات إضافية (اختياري)",
  commentsPlaceholder: "قدم المزيد من التفاصيل هنا...",
  selectReasonError: "يرجى اختيار سبب للإبلاغ.",
  descriptionLengthError: "لا يمكن أن يتجاوز الوصف 500 حرف.",
  reportSentSuccess: "تم إرسال التقرير بنجاح! سيتم مراجعته قريباً.",
  reportSendError: "فشل إرسال التقرير. يرجى المحاولة مرة أخرى.",
  duplicateReportError: "لقد قمت بالفعل بإرسال هذا التقرير نفسه.",
  selfReportError: "لا يمكنك الإبلاغ عن نفسك.",
  targetNotFoundError: "الكتاب أو المستخدم غير موجود.",
  serverError: "خطأ في الخادم. يرجى المحاولة مرة أخرى لاحقاً.",
  reportTitle: "الإبلاغ عن محتوى غير لائق",
  reportDescription:
    "يرجى اختيار سبب وتقديم التفاصيل أدناه. ملاحظاتك تساعد في الحفاظ على مجتمعنا آمناً.",
  reasonForReporting: "سبب الإبلاغ",
  selectReason: "اختر سبباً",
  inappropriateContent: "محتوى غير لائق",
  spamOrFake: "محتوى مزعج أو مزيف",
  offensiveLanguage: "لغة مسيئة",
  harassment: "تحرش",
  scamOrFraud: "احتيال أو غش",
  other: "أخرى",
  reportUser: "الإبلاغ عن مستخدم",
  invalidReportTarget: "هدف الإبلاغ غير صالح.",
  suggest: "اقتراح",
  suggestCategoryTitle: "اقتراح فئة",
  suggestCategoryDescription: "ساعدنا في التحسين باقتراح فئة كتب جديدة",
  categoryName: "اسم الفئة",
  categoryPlaceholder: "مثال: الخيال العلمي، التاريخ...",
  characters: "حرف",
  requirements: "المتطلبات",
  atLeastThreeChars: "3 أحرف على الأقل",
  noNumbers: "لا يسمح بالأرقام",
  maxFiftyChars: "50 حرف كحد أقصى",
  submitting: "جاري الإرسال...",
  submitSuggestion: "تقديم الاقتراح",
  noNumbersError: "اسم الفئة لا يمكن أن يحتوي على أرقام",
  minCharactersError: "يجب أن يكون اسم الفئة 3 أحرف على الأقل",
  maxCharactersError: "يجب ألا يتجاوز اسم الفئة 50 حرف",
  viewDetails: "عرض التفاصيل",
  confirmBookRemoval: "تأكيد إزالة الكتاب",
  removeBookConfirmation:
    "هل أنت متأكد أنك تريد إزالة هذا الكتاب من قائمة المفضلة؟ لا يمكن التراجع عن هذا الإجراء.",
  yesRemove: "نعم، إزالة",
  remove: "إزالة",
  clearWishlist: "مسح قائمة المفضلة",
  confirmClearWishlist: "تأكيد مسح قائمة المفضلة",
  clearWishlistConfirmation:
    "هل أنت متأكد أنك تريد إزالة جميع العناصر من قائمة المفضلة؟ لا يمكن التراجع عن هذا الإجراء.",
  yesClear: "نعم، مسح",
  wishlistCleared: "تم مسح قائمة المفضلة بنجاح!",
  emptyWishlistTitle: "قائمة المفضلة فارغة",
  emptyWishlistSubtitle: "أضف كتبك المفضلة واعثر عليها هنا لاحقاً.",
  mySavedBooks: "كتبي المحفوظة",
  loadingWishlist: "جاري تحميل قائمة المفضلة...",
  home: "الرئيسية",
  addBook: "إضافة كتاب",
  wishlist: "المفضلة",
  notification: "الإشعارات",
  myProfile: "ملفي",
  logout: "تسجيل الخروج",
  language: "اللغة",

  //order page
  noBookFound: "لم يتم العثور على كتاب.",
  selectDates: "من فضلك اختر تاريخ البداية والنهاية.",
  endDateAfterStart: "يجب أن يكون تاريخ الانتهاء بعد تاريخ البداية.",
  requestSuccess: "تم إرسال الطلب بنجاح.",
  errorMessage: "حدث خطأ ما.",
  notAvailable: "غير متاح",
  free: "مجاني",
  currency: "جنيه",
  perDay: "يوم",
  noDescription: "لا يوجد وصف متاح.",
  selectBorrowDuration: "اختر مدة الاستعارة:",
  startDate: "تاريخ البداية",
  endDate: "تاريخ الانتهاء",
  reservedDays: "الأيام المحجوزة (غير متاحة)",
  confirmOperation: "تأكيد العملية",
  confirmMessage: "هل أنت متأكد أنك تريد إتمام هذه",
  cancel: "إلغاء",
  confirm: "تأكيد",
  operationSummary: "ملخص العملية",
  reviewOrderDetails: "من فضلك راجع تفاصيل الطلب.",
  operation: "العملية",
  borrowDays: "أيام الاستعارة",
  days: "يوم",
  pricePerDay: "السعر لكل يوم",
  total: "الإجمالي",
  selectValidDates: "اختر تواريخ صحيحة",
  free: "مجاني",
  process: "تنفيذ",
  currency: "جنيه",
  buy: "شراء",
  borrow: "استعارة",
  donate: "تبرع",
  toSale: "للبيع",
  toBorrow: "استعارة",
  toDonate: "تبرع",

  //Edit book page
  editBookTitle: "تعديل الكتاب",
  onlyImagesAllowed: "مسموح فقط برفع صور",
  imageTooLarge: "يجب أن تكون الصورة أقل من 5 ميجابايت",
  priceNegative: "لا يمكن أن يكون السعر سالباً",
  titleTooShort: "يجب أن يكون العنوان مكوناً من حرفين على الأقل",
  categoryRequired: "الفئة مطلوبة",
  descriptionTooShort: "يجب أن يكون الوصف مكوناً من 10 أحرف على الأقل",
  priceRequired: "السعر مطلوب",
  pricePerDayRequired: "سعر اليوم مطلوب",
  priceMustBePositive: "يجب أن يكون السعر أكبر من صفر",
  pricePerDayMustBePositive: "يجب أن يكون السعر لليوم أكبر من صفر",
  updatingBook: "جاري تحديث الكتاب...",
  bookUpdatedSuccess: "تم تحديث الكتاب بنجاح!",
  redirectingProfile: "إعادة التوجيه إلى ملفك الشخصي...",
  updateBook: "تحديث الكتاب",
  cancel: "إلغاء",
  title: "العنوان",
  selectCategory: "اختر الفئة",
  price: "السعر",
  pricePerDay: "السعر لكل يوم",
  description: "الوصف",
  currentImage: "الصورة الحالية:",
  bookCoverAlt: "غلاف الكتاب",
  newImage: "صورة جديدة",
  changeBookCoverOptional: "تغيير غلاف الكتاب (اختياري)",
  bookCoverPreview: "معاينة غلاف الكتاب",
  newImage: "صورة جديدة",
  currentImage: "الصورة الحالية",
  changeImage: "تغيير الصورة",
  changeBookCover: "تغيير غلاف الكتاب",
  uploadBookCover: "رفع غلاف الكتاب",
  chooseDifferentImage: "اضغط لاختيار صورة أخرى",
  keepCurrentImage: "سيتم الاحتفاظ بالصورة الحالية إذا لم تقم برفع صورة جديدة",
  uploadImageHelp: "قم برفع صورة (بحد أقصى 5 ميجابايت)",

  //Notificatio
  invitations: "الدعوات",
  notifications: "الإشعارات",
  noNotifications: "لا توجد إشعارات",
  accept: "قبول",
  refuse: "رفض",
  invalidPaymentNotification: "إشعار دفع غير صالح.",
  paymentFailed: "فشل الدفع",
  paymentFailedTryAgain: "فشل الدفع. يرجى المحاولة مرة أخرى.",
  processing: "جاري المعالجة...",
  payNow: "ادفع الآن",
  completePayment: "أكمل عملية الدفع",
  close: "إغلاق",
  notifications: "الإشعارات",
  noNotificationsYet: "لا توجد إشعارات بعد",
  actionRequired: "مطلوب إجراء",
  recentActivity: "النشاط الأخير",
  justNow: "الآن",
  minutesAgo: " دقيقة مضت",
  hoursAgo: " ساعة مضت",
  daysAgo: " يوم مضى",
  request: "طلب",
  accept: "قبول",
  refuse: "رفض",
  writeReasonForRefusal: "اكتب سبب الرفض",
  reason: "السبب",
  cancel: "إلغاء",
  sendRefusal: "إرسال الرفض",
  switchToArabic: "التبديل إلى العربية",
  switchToEnglish: "التبديل إلى الإنجليزية",

  // Profile Page
  loadingProfile: "جاري تحميل الملف الشخصي...",
  errorLoadingProfile: "خطأ في تحميل الملف الشخصي",
  retry: "إعادة المحاولة",
  myBooks: "كتبي",
  memberSince: "عضو منذ:",
  removeProfilePicture: "إزالة صورة الملف الشخصي",
  clickToChangeProfilePicture: "انقر لتغيير صورة الملف الشخصي",
  myReports: "تقاريري",
  editProfilePicture: "تعديل صورة الملف الشخصي",
  remove: "إزالة",
  profilePictureRemoved: "تم إزالة صورة الملف الشخصي، استخدام الصورة الافتراضية",
  profilePictureUploadSuccess: "تم رفع الصورة بنجاح",
  profilePictureUploadError: "خطأ في رفع الصورة",
  
  // Public Profile Page
  usersBooks: "كتب المستخدم",
  reportUser: "الإبلاغ عن المستخدم",
  friends: "الأصدقاء",
  
  // Book Card
  confirmDelete: "تأكيد الحذف",
  deleteBookConfirmation: "هل أنت متأكد أنك تريد حذف هذا الكتاب؟",
  editBook: "تعديل الكتاب",
  deleteBook: "حذف الكتاب",
  pendingOrder: "طلب قيد الانتظار",
  bookCoverOf: "غلاف كتاب",
  
  // Books Grid
  noBooksFound: "لم يتم العثور على كتب",
  
  // Profile Header
  profileImage: "صورة الملف الشخصي",
  
  // Tab Navigation
  myBooksTab: "كتبي",
  
  // Add Book Form
  addNewBook: "إضافة كتاب جديد",
  author: "المؤلف",
  status: "الحالة",
  forShare: "للمشاركة",
  forSale: "للبيع",
  forDonation: "للتبرع",
  imageURL: "رابط الصورة",
  addBook: "إضافة كتاب",
  bookData: "بيانات الكتاب:",

  // Existing translations
  bookRemoved: "تم إزالة الكتاب من المفضلة",
  bookAdded: "تمت إضافة الكتاب إلى المفضلة",
  errorMessage: "حدث خطأ ما.",
  forSale: "للبيع",
  currentlyBorrowed: "الكتاب مُعار حالياً (يمكنك حجز فترة أخرى)",
  availableToBorrow: "متاح للاستعارة",
  availableToExchange: "متاح للتبادل",
  freeToDonate: "متاح للتبرع",
  bookNotFound: "الكتاب غير موجود أو غير متاح.",
  general: "عام",
  proceedToOrder: "إتمام الطلب",
  reportBook: "الإبلاغ عن هذا الكتاب",
  by: "بواسطة",
  unknownAuthor: "مؤلف غير معروف",
  listedBy: "مدرج بواسطة:",
  unknown: "غير معروف",
  home: "الرئيسية",
  category: "الفئة",
  currency: "جنيه",
  noReportsFound: "لا توجد تقارير",
  noReportsDescription: "لم تقم بإرسال أي تقارير بعد. استكشف الكتب وقم بالإبلاغ عن أي مشاكل تجدها.",
  browseBooks: "تصفح الكتب",
  targetType: "نوع الهدف",
  all: "الكل",
  pending: "قيد الانتظار",
  reviewed: "تم المراجعة",
  dismissed: "مرفوض",
  cancelled: "ملغى",
  user: "مستخدم",
  book: "كتاب",
  mySubmittedReports: "تقاريري المقدمة",
  showingResults: "عرض {start} إلى {end} من أصل {total} نتيجة",
  target: "الهدف",
  reason: "السبب",
  dateSubmitted: "تاريخ الإرسال",
  action: "إجراء",
  userNotFound: "المستخدم غير موجود",
  bookNotFound: "الكتاب غير موجود",
  confirmCancelReport: "تأكيد إلغاء التقرير",
  cancelReportConfirmation: "هل أنت متأكد أنك تريد إلغاء هذا التقرير؟ لا يمكن التراجع عن هذا الإجراء.",
  no: "لا",
  yesCancel: "نعم، إلغاء",
  cancel: "إلغاء",
  sendReport: "إرسال التقرير",
  sending: "جاري الإرسال...",
  additionalComments: "تعليقات إضافية (اختياري)",
  commentsPlaceholder: "قدم المزيد من التفاصيل هنا...",
  selectReasonError: "يرجى اختيار سبب للإبلاغ.",
  descriptionLengthError: "لا يمكن أن يتجاوز الوصف 500 حرف.",
  reportSentSuccess: "تم إرسال التقرير بنجاح! سيتم مراجعته قريباً.",
  reportSendError: "فشل إرسال التقرير. يرجى المحاولة مرة أخرى.",
  duplicateReportError: "لقد قمت بالفعل بإرسال هذا التقرير نفسه.",
  selfReportError: "لا يمكنك الإبلاغ عن نفسك.",
  targetNotFoundError: "الكتاب أو المستخدم غير موجود.",
  serverError: "خطأ في الخادم. يرجى المحاولة مرة أخرى لاحقاً.",
  reportTitle: "الإبلاغ عن محتوى غير لائق",
  reportDescription: "يرجى اختيار سبب وتقديم التفاصيل أدناه. ملاحظاتك تساعد في الحفاظ على مجتمعنا آمناً.",
  reasonForReporting: "سبب الإبلاغ",
  selectReason: "اختر سبباً",
  inappropriateContent: "محتوى غير لائق",
  spamOrFake: "محتوى مزعج أو مزيف",
  offensiveLanguage: "لغة مسيئة",
  harassment: "تحرش",
  scamOrFraud: "احتيال أو غش",
  other: "أخرى",
  invalidReportTarget: "هدف الإبلاغ غير صالح.",
  suggest: "اقتراح",
  suggestCategoryTitle: "اقتراح فئة",
  suggestCategoryDescription: "ساعدنا في التحسين باقتراح فئة كتب جديدة",
  categoryName: "اسم الفئة",
  categoryPlaceholder: "مثال: الخيال العلمي، التاريخ...",
  characters: "حرف",
  requirements: "المتطلبات",
  atLeastThreeChars: "3 أحرف على الأقل",
  noNumbers: "لا يسمح بالأرقام",
  maxFiftyChars: "50 حرف كحد أقصى",
  submitting: "جاري الإرسال...",
  submitSuggestion: "تقديم الاقتراح",
  noNumbersError: "اسم الفئة لا يمكن أن يحتوي على أرقام",
  minCharactersError: "يجب أن يكون اسم الفئة 3 أحرف على الأقل",
  maxCharactersError: "يجب ألا يتجاوز اسم الفئة 50 حرف",
  viewDetails: "عرض التفاصيل",
  confirmBookRemoval: "تأكيد إزالة الكتاب",
  removeBookConfirmation: "هل أنت متأكد أنك تريد إزالة هذا الكتاب من قائمة المفضلة؟ لا يمكن التراجع عن هذا الإجراء.",
  yesRemove: "نعم، إزالة",
  clearWishlist: "مسح قائمة المفضلة",
  confirmClearWishlist: "تأكيد مسح قائمة المفضلة",
  clearWishlistConfirmation: "هل أنت متأكد أنك تريد إزالة جميع العناصر من قائمة المفضلة؟ لا يمكن التراجع عن هذا الإجراء.",
  yesClear: "نعم، مسح",
  wishlistCleared: "تم مسح قائمة المفضلة بنجاح!",
  emptyWishlistTitle: "قائمة المفضلة فارغة",
  emptyWishlistSubtitle: "أضف كتبك المفضلة واعثر عليها هنا لاحقاً.",
  mySavedBooks: "كتبي المحفوظة",
  loadingWishlist: "جاري تحميل قائمة المفضلة...",
  wishlist: "المفضلة",
  notification: "الإشعارات",
  myProfile: "ملفي",
  logout: "تسجيل الخروج",
  language: "اللغة",
  noBookFound: "لم يتم العثور على كتاب.",
  selectDates: "من فضلك اختر تاريخ البداية والنهاية.",
  endDateAfterStart: "يجب أن يكون تاريخ الانتهاء بعد تاريخ البداية.",
  requestSuccess: "تم إرسال الطلب بنجاح.",
  notAvailable: "غير متاح",
  free: "مجاني",
  perDay: "يوم",
  noDescription: "لا يوجد وصف متاح.",
  selectBorrowDuration: "اختر مدة الاستعارة:",
  startDate: "تاريخ البداية",
  endDate: "تاريخ الانتهاء",
  reservedDays: "الأيام المحجوزة (غير متاحة)",
  confirmOperation: "تأكيد العملية",
  confirmMessage: "هل أنت متأكد أنك تريد إتمام هذه",
  confirm: "تأكيد",
  operationSummary: "ملخص العملية",
  reviewOrderDetails: "من فضلك راجع تفاصيل الطلب.",
  operation: "العملية",
  borrowDays: "أيام الاستعارة",
  days: "يوم",
  pricePerDay: "السعر لكل يوم",
  total: "الإجمالي",
  selectValidDates: "اختر تواريخ صحيحة",
  process: "تنفيذ",
  buy: "شراء",
  borrow: "استعارة",
  donate: "تبرع",
  toBorrow: "استعارة",
  toDonate: "تبرع",
  editBookTitle: "تعديل الكتاب",
  onlyImagesAllowed: "مسموح فقط برفع صور",
  imageTooLarge: "يجب أن تكون الصورة أقل من 5 ميجابايت",
  priceNegative: "لا يمكن أن يكون السعر سالباً",
  titleTooShort: "يجب أن يكون العنوان مكوناً من حرفين على الأقل",
  categoryRequired: "الفئة مطلوبة",
  descriptionTooShort: "يجب أن يكون الوصف مكوناً من 10 أحرف على الأقل",
  priceRequired: "السعر مطلوب",
  pricePerDayRequired: "سعر اليوم مطلوب",
  priceMustBePositive: "يجب أن يكون السعر أكبر من صفر",
  pricePerDayMustBePositive: "يجب أن يكون السعر لليوم أكبر من صفر",
  updatingBook: "جاري تحديث الكتاب...",
  bookUpdatedSuccess: "تم تحديث الكتاب بنجاح!",
  redirectingProfile: "إعادة التوجيه إلى ملفك الشخصي...",
  updateBook: "تحديث الكتاب",
  title: "العنوان",
  selectCategory: "اختر الفئة",
  price: "السعر",
  pricePerDay: "السعر لكل يوم",
  description: "الوصف",
  currentImage: "الصورة الحالية:",
  bookCoverAlt: "غلاف الكتاب",
  newImage: "صورة جديدة",
  changeBookCoverOptional: "تغيير غلاف الكتاب (اختياري)",
  bookCoverPreview: "معاينة غلاف الكتاب",
  changeImage: "تغيير الصورة",
  changeBookCover: "تغيير غلاف الكتاب",
  uploadBookCover: "رفع غلاف الكتاب",
  chooseDifferentImage: "اضغط لاختيار صورة أخرى",
  keepCurrentImage: "سيتم الاحتفاظ بالصورة الحالية إذا لم تقم برفع صورة جديدة",
  uploadImageHelp: "قم برفع صورة (بحد أقصى 5 ميجابايت)",
  invitations: "الدعوات",
  notifications: "الإشعارات",
  noNotifications: "لا توجد إشعارات",
  accept: "قبول",
  refuse: "رفض",
  invalidPaymentNotification: "إشعار دفع غير صالح.",
  paymentFailed: "فشل الدفع",
  paymentFailedTryAgain: "فشل الدفع. يرجى المحاولة مرة أخرى.",
  processing: "جاري المعالجة...",
  payNow: "ادفع الآن",
  completePayment: "أكمل عملية الدفع",
  close: "إغلاق",
  noNotificationsYet: "لا توجد إشعارات بعد",
  actionRequired: "مطلوب إجراء",
  recentActivity: "النشاط الأخير",
  justNow: "الآن",
  minutesAgo: " دقيقة مضت",
  hoursAgo: " ساعة مضت",
  daysAgo: " يوم مضى",
  request: "طلب",
  writeReasonForRefusal: "اكتب سبب الرفض",
  sendRefusal: "إرسال الرفض",
  switchToArabic: "التبديل إلى العربية",
  switchToEnglish: "التبديل إلى الإنجليزية",
};

export default ar;
