const ar = {
  //Book Details
  bookRemoved: 'تم إزالة الكتاب من المفضلة',
  bookAdded: 'تمت إضافة الكتاب إلى المفضلة',
  errorMessage: 'حدث خطأ ما.',
  forSale: 'للبيع',
  currentlyBorrowed: 'الكتاب مُعار حالياً (يمكنك حجز فترة أخرى)',
  availableToBorrow: 'متاح للاستعارة',
  availableToExchange: 'متاح للتبادل',
  freeToDonate: 'متاح للتبرع',
  bookNotFound: 'الكتاب غير موجود أو غير متاح.',
  general: 'عام',
  proceedToOrder: 'إتمام الطلب',
  reportBook: 'الإبلاغ عن هذا الكتاب',
  by: 'بواسطة',
  unknownAuthor: 'مؤلف غير معروف',
  listedBy: 'مدرج بواسطة:',
  unknown: 'غير معروف',
  home: 'الرئيسية',
  category: 'الفئة',
  currency: 'جنيه',
  noReportsFound: 'لا توجد تقارير',
  noReportsDescription: 'لم تقم بإرسال أي تقارير بعد. استكشف الكتب وقم بالإبلاغ عن أي مشاكل تجدها.',
  browseBooks: 'تصفح الكتب',
  status: 'الحالة',
  targetType: 'نوع الهدف',
  all: 'الكل',
  pending: 'قيد الانتظار',
  reviewed: 'تم المراجعة',
  dismissed: 'مرفوض',
  cancelled: 'ملغى',
  user: 'مستخدم',
  book: 'كتاب',
  mySubmittedReports: 'تقاريري المقدمة',
  showingResults: 'عرض {start} إلى {end} من أصل {total} نتيجة',
  target: 'الهدف',
  reason: 'السبب',
  dateSubmitted: 'تاريخ الإرسال',
  action: 'إجراء',
  userNotFound: 'المستخدم غير موجود',
  bookNotFound: 'الكتاب غير موجود',
  confirmCancelReport: 'تأكيد إلغاء التقرير',
  cancelReportConfirmation:
    'هل أنت متأكد أنك تريد إلغاء هذا التقرير؟ لا يمكن التراجع عن هذا الإجراء.',
  no: 'لا',
  yesCancel: 'نعم، إلغاء',
  cancel: 'إلغاء',
  pending: 'قيد الانتظار',
  reviewed: 'تم المراجعة',
  dismissed: 'مرفوض',
  cancelled: 'ملغى',
  sendReport: 'إرسال التقرير',
  sending: 'جاري الإرسال...',
  reportBook: 'الإبلاغ عن الكتاب',
  additionalComments: 'تعليقات إضافية (اختياري)',
  commentsPlaceholder: 'قدم المزيد من التفاصيل هنا...',
  selectReasonError: 'يرجى اختيار سبب للإبلاغ.',
  descriptionLengthError: 'لا يمكن أن يتجاوز الوصف 500 حرف.',
  reportSentSuccess: 'تم إرسال التقرير بنجاح! سيتم مراجعته قريباً.',
  reportSendError: 'فشل إرسال التقرير. يرجى المحاولة مرة أخرى.',
  duplicateReportError: 'لقد قمت بالفعل بإرسال هذا التقرير نفسه.',
  selfReportError: 'لا يمكنك الإبلاغ عن نفسك.',
  targetNotFoundError: 'الكتاب أو المستخدم غير موجود.',
  serverError: 'خطأ في الخادم. يرجى المحاولة مرة أخرى لاحقاً.',
  reportTitle: 'الإبلاغ عن محتوى غير لائق',
  reportDescription:
    'يرجى اختيار سبب وتقديم التفاصيل أدناه. ملاحظاتك تساعد في الحفاظ على مجتمعنا آمناً.',
  reasonForReporting: 'سبب الإبلاغ',
  selectReason: 'اختر سبباً',
  inappropriateContent: 'محتوى غير لائق',
  spamOrFake: 'محتوى مزعج أو مزيف',
  offensiveLanguage: 'لغة مسيئة',
  harassment: 'تحرش',
  scamOrFraud: 'احتيال أو غش',
  other: 'أخرى',
  reportUser: 'الإبلاغ عن مستخدم',
  invalidReportTarget: 'هدف الإبلاغ غير صالح.',
  suggest: 'اقتراح',
  suggestCategoryTitle: 'اقتراح فئة',
  suggestCategoryDescription: 'ساعدنا في التحسين باقتراح فئة كتب جديدة',
  categoryName: 'اسم الفئة',
  categoryPlaceholder: 'مثال: الخيال العلمي، التاريخ...',
  characters: 'حرف',
  requirements: 'المتطلبات',
  atLeastThreeChars: '3 أحرف على الأقل',
  noNumbers: 'لا يسمح بالأرقام',
  maxFiftyChars: '50 حرف كحد أقصى',
  submitting: 'جاري الإرسال...',
  submitSuggestion: 'تقديم الاقتراح',
  noNumbersError: 'اسم الفئة لا يمكن أن يحتوي على أرقام',
  minCharactersError: 'يجب أن يكون اسم الفئة 3 أحرف على الأقل',
  maxCharactersError: 'يجب ألا يتجاوز اسم الفئة 50 حرف',
  viewDetails: 'عرض التفاصيل',
  confirmBookRemoval: 'تأكيد إزالة الكتاب',
  removeBookConfirmation:
    'هل أنت متأكد أنك تريد إزالة هذا الكتاب من قائمة المفضلة؟ لا يمكن التراجع عن هذا الإجراء.',
  yesRemove: 'نعم، إزالة',
  remove: 'إزالة',
  clearWishlist: 'مسح قائمة المفضلة',
  confirmClearWishlist: 'تأكيد مسح قائمة المفضلة',
  clearWishlistConfirmation:
    'هل أنت متأكد أنك تريد إزالة جميع العناصر من قائمة المفضلة؟ لا يمكن التراجع عن هذا الإجراء.',
  yesClear: 'نعم، مسح',
  wishlistCleared: 'تم مسح قائمة المفضلة بنجاح!',
  emptyWishlistTitle: 'قائمة المفضلة فارغة',
  emptyWishlistSubtitle: 'أضف كتبك المفضلة واعثر عليها هنا لاحقاً.',
  mySavedBooks: 'كتبي المحفوظة',
  loadingWishlist: 'جاري تحميل قائمة المفضلة...',
  home: 'الرئيسية',
  addBook: 'إضافة كتاب',
  wishlist: 'المفضلة',
  notification: 'الإشعارات',
  myProfile: 'ملفي',
  logout: 'تسجيل الخروج',
  language: 'اللغة',

  profile: {
    // Profile Header
    myReports: "تقاريري",
    changeProfilePicture: "تغيير صورة الملف الشخصي",
    memberSince: "عضو منذ",
    
    // Tab Navigation
    myBooks: "كتبي",
    userBooks: "كتب المستخدم",
    
    // Books Grid
    noBooksFound: "لم يتم العثور على كتب",
    noBooksDescription: "لا توجد كتب لعرضها حالياً",
    
    // Book Card
    forSale: "للبيع",
    forBorrow: "للإعارة", 
    forExchange: "للمبادلة",
    forDonation: "للتبرع",
    pendingOrder: "طلب قيد الانتظار",
    editBook: "تعديل الكتاب",
    deleteBook: "حذف الكتاب",
    confirmDelete: "تأكيد الحذف",
    deleteConfirmation: "هل أنت متأكد أنك تريد حذف هذا الكتاب؟",
    cancel: "إلغاء",
    delete: "حذف",
    
    // Public Profile
    reportUser: "الإبلاغ عن المستخدم",
    friends: "أصدقاء",
    
    // Loading States
    loadingProfile: "جاري تحميل الملف الشخصي...",
    loadingBooks: "جاري تحميل الكتب...",
    
    // Error States
    errorLoadingProfile: "خطأ في تحميل الملف الشخصي",
    errorLoadingBooks: "خطأ في تحميل الكتب",
    retry: "إعادة المحاولة"
  },
};

export default ar;
