const en = {
  //Book Details
  bookRemoved: "Book removed from wishlist",
  bookAdded: "Book added to wishlist",
  errorMessage: "Something went wrong.",
  forSale: "For Sale",
  currentlyBorrowed: "Currently borrowed (you can reserve another period)",
  availableToBorrow: "Available to Borrow",
  availableToExchange: "Available to Exchange",
  freeToDonate: "Free to Donate",
  bookNotFound: "Book not found or unavailable.",
  general: "General",
  proceedToOrder: "Proceed to Order",
  reportBook: "Report this book",
  by: "by",
  unknownAuthor: "Unknown Author",
  listedBy: "Listed By:",
  unknown: "Unknown",
  home: "Home",
  category: "Category",
  currency: "EGP",
  noReportsFound: "No Reports Found",
  noReportsDescription:
    "You haven't submitted any reports yet. Explore books and report any issues you find.",
  browseBooks: "Browse Books",
  status: "Status",
  targetType: "Target Type",
  all: "All",
  pending: "Pending",
  reviewed: "Reviewed",
  dismissed: "Dismissed",
  cancelled: "Cancelled",
  user: "User",
  book: "Book",
  mySubmittedReports: "My Submitted Reports",
  showingResults: "Showing {start} to {end} of {total} results",
  target: "Target",
  reason: "Reason",
  dateSubmitted: "Date Submitted",
  action: "Action",
  userNotFound: "User Not Found",
  bookNotFound: "Book Not Found",
  confirmCancelReport: "Confirm Cancel Report",
  cancelReportConfirmation:
    "Are you sure you want to cancel this report? This action cannot be undone.",
  no: "No",
  yesCancel: "Yes, Cancel",
  cancel: "Cancel",
  pending: "Pending",
  reviewed: "Reviewed",
  dismissed: "Dismissed",
  cancelled: "Cancelled",
  sendReport: "Send Report",
  sending: "Sending...",
  reportBook: "Report Book",
  additionalComments: "Additional Comments (Optional)",
  commentsPlaceholder: "Provide more details here...",
  selectReasonError: "Please select a reason for reporting.",
  descriptionLengthError: "Description cannot exceed 500 characters.",
  reportSentSuccess: "Report sent successfully! It will be reviewed shortly.",
  reportSendError: "Failed to send report. Please try again.",
  duplicateReportError: "You have already submitted this exact report.",
  selfReportError: "You cannot report yourself.",
  targetNotFoundError: "Book or user not found.",
  serverError: "Server error. Please try again later.",
  reportTitle: "Report Inappropriate Content",
  reportDescription:
    "Please select a reason and provide details below. Your feedback helps keep our community safe.",
  reasonForReporting: "Reason for Reporting",
  selectReason: "Select a reason",
  inappropriateContent: "Inappropriate Content",
  spamOrFake: "Spam or Fake",
  offensiveLanguage: "Offensive Language",
  harassment: "Harassment",
  scamOrFraud: "Scam or Fraud",
  other: "Other",
  reportUser: "Report User",
  invalidReportTarget: "Invalid report target.",
  suggest: "Suggest",
  suggestCategoryTitle: "Suggest a Category",
  suggestCategoryDescription:
    "Help us improve by suggesting a new book category",
  categoryName: "Category Name",
  categoryPlaceholder: "e.g., Science Fiction, History...",
  characters: "characters",
  requirements: "Requirements",
  atLeastThreeChars: "At least 3 characters",
  noNumbers: "No numbers allowed",
  maxFiftyChars: "Maximum 50 characters",
  submitting: "Submitting...",
  submitSuggestion: "Submit Suggestion",
  noNumbersError: "Category name cannot contain numbers",
  minCharactersError: "Category name must be at least 3 characters",
  maxCharactersError: "Category name must not exceed 50 characters",
  viewDetails: "View Details",
  confirmBookRemoval: "Confirm Book Removal",
  removeBookConfirmation:
    "Are you sure you want to remove this book from your wishlist? This action cannot be undone.",
  yesRemove: "Yes, Remove",
  remove: "Remove",
  clearWishlist: "Clear Wishlist",
  confirmClearWishlist: "Confirm Clear Wishlist",
  clearWishlistConfirmation:
    "Are you sure you want to remove all items from your wishlist? This action cannot be undone.",
  yesClear: "Yes, Clear",
  wishlistCleared: "Wishlist cleared successfully!",
  emptyWishlistTitle: "Your wishlist is empty",
  emptyWishlistSubtitle: "Add your favorite books and find them here later.",
  mySavedBooks: "My Saved Books",
  loadingWishlist: "Loading wishlist...",
  home: "Home",
  addBook: "Add Book",
  wishlist: "Wishlist",
  notification: "Notification",
  myProfile: "My Profile",
  logout: "Logout",
  language: "Language",

  //order page
  noBookFound: "No book found.",
  selectDates: "Please select both start and end dates.",
  endDateAfterStart: "End date must be after start date.",
  requestSuccess: "Request sent successfully.",
  errorMessage: "Something went wrong.",
  notAvailable: "N/A",
  free: "Free",
  currency: "EGP",
  perDay: "day",
  noDescription: "No description available.",
  selectBorrowDuration: "Select Borrow Duration:",
  startDate: "Start Date",
  endDate: "End Date",
  reservedDays: "Reserved days (not available)",
  confirmOperation: "Confirm Operation",
  confirmMessage: "Are you sure you want to complete this",
  cancel: "Cancel",
  confirm: "Confirm",
  operationSummary: "Operation Summary",
  reviewOrderDetails: "Please review your order details.",
  operation: "Operation",
  borrowDays: "Borrow days",
  days: "day(s)",
  pricePerDay: "Price per day",
  total: "Total",
  selectValidDates: "Select valid dates",
  free: "Free",
  process: "Process",
  currency: "EGP",
  buy: "Buy",
  borrow: "Borrow",
  donate: "Donate",
  toSale: "For Sale",
  toBorrow: "Borrow",
  toDonate: "Donate",

  //Edit book page
  editBookTitle: "Edit Your Book",
  onlyImagesAllowed: "Only image files are allowed",
  imageTooLarge: "Image must be less than 5MB",
  priceNegative: "Price cannot be negative",
  titleTooShort: "Title must be at least 2 characters",
  categoryRequired: "Category is required",
  descriptionTooShort: "Description must be at least 10 characters",
  priceRequired: "Price is required",
  pricePerDayRequired: "Price per day is required",
  priceMustBePositive: "Price must be greater than zero",
  pricePerDayMustBePositive: "Price per day must be greater than zero",
  updatingBook: "Updating your book...",
  bookUpdatedSuccess: "Book updated successfully!",
  redirectingProfile: "Redirecting to your profile...",
  updateBook: "Update Book",
  cancel: "Cancel",
  title: "Title",
  selectCategory: "Select category",
  price: "Price",
  pricePerDay: "Price Per Day",
  description: "Description",
  currentImage: "Current Image:",
  bookCoverAlt: "Book cover",
  newImage: "New Image",
  changeBookCoverOptional: "Change Book Cover (Optional)",
  bookCoverPreview: "Book cover preview",
  newImage: "New Image",
  currentImage: "Current Image",
  changeImage: "Change Image",
  changeBookCover: "Change Book Cover",
  uploadBookCover: "Upload Book Cover",
  chooseDifferentImage: "Click to choose a different image",
  keepCurrentImage: "Current image will be kept if you don't upload a new one",
  uploadImageHelp: "Upload an image (max 5MB)",

  //notification
  invitations: "Invitations",
  notifications: "Notifications",
  noNotifications: "No notifications",
  accept: "Accept",
  refuse: "Refuse",
invalidPaymentNotification: "Invalid payment notification.",
  paymentFailed: "Payment failed",
  paymentFailedTryAgain: "Payment failed. Please try again.",
  processing: "Processing...",
  payNow: "Pay Now",
  completePayment: "Complete Your Payment",
  close: "Close",
notifications: "Notifications",
  noNotificationsYet: "No notifications yet",
  actionRequired: "ACTION REQUIRED",
  recentActivity: "Recent Activity",
  justNow: "just now",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
request: "Request",
  accept: "Accept",
  refuse: "Refuse",
  writeReasonForRefusal: "Write the reason for refusal",
  reason: "Reason",
  cancel: "Cancel",
  sendRefusal: "Send Refusal",
switchToArabic: "Switch to Arabic",
  switchToEnglish: "Switch to English",

  // Profile Page
  loadingProfile: "Loading profile...",
  errorLoadingProfile: "Error loading profile",
  retry: "Retry",
  myBooks: "My Books",
  memberSince: "Member since:",
  removeProfilePicture: "Remove Profile Picture",
  clickToChangeProfilePicture: "Click to change profile picture",
  myReports: "My Reports",
  editProfilePicture: "Edit Profile Picture",
  remove: "Remove",
  profilePictureRemoved: "Profile image removed, using default image",
  profilePictureUploadSuccess: "Image upload successful",
  profilePictureUploadError: "Error uploading image",
  
  // Public Profile Page
  usersBooks: "User's Books",
  reportUser: "Report User",
  friends: "Friends",
  
  // Book Card
  confirmDelete: "Confirm Delete",
  deleteBookConfirmation: "Are you sure you want to delete this book?",
  editBook: "Edit Book",
  deleteBook: "Delete Book",
  pendingOrder: "Pending Order",
  bookCoverOf: "Book cover of",
  
  // Books Grid
  noBooksFound: "No books found",
  
  // Profile Header
  profileImage: "Profile Image",
  
  // Tab Navigation
  myBooksTab: "My Books",
  
  // Add Book Form
  addNewBook: "Add New Book",
  author: "Author",
  status: "Status",
  forShare: "For Share",
  forSale: "For Sale",
  forDonation: "For Donation",
  imageURL: "Image URL",
  addBook: "Add Book",
  bookData: "Book data:",

  // Existing translations
  bookRemoved: "Book removed from wishlist",
  bookAdded: "Book added to wishlist",
  errorMessage: "Something went wrong.",
  forSale: "For Sale",
  currentlyBorrowed: "Currently borrowed (you can reserve another period)",
  availableToBorrow: "Available to Borrow",
  availableToExchange: "Available to Exchange",
  freeToDonate: "Free to Donate",
  bookNotFound: "Book not found or unavailable.",
  general: "General",
  proceedToOrder: "Proceed to Order",
  reportBook: "Report this book",
  by: "by",
  unknownAuthor: "Unknown Author",
  listedBy: "Listed By:",
  unknown: "Unknown",
  home: "Home",
  category: "Category",
  currency: "EGP",
  noReportsFound: "No Reports Found",
  noReportsDescription: "You haven't submitted any reports yet. Explore books and report any issues you find.",
  browseBooks: "Browse Books",
  targetType: "Target Type",
  all: "All",
  pending: "Pending",
  reviewed: "Reviewed",
  dismissed: "Dismissed",
  cancelled: "Cancelled",
  user: "User",
  book: "Book",
  mySubmittedReports: "My Submitted Reports",
  showingResults: "Showing {start} to {end} of {total} results",
  target: "Target",
  reason: "Reason",
  dateSubmitted: "Date Submitted",
  action: "Action",
  userNotFound: "User Not Found",
  confirmCancelReport: "Confirm Cancel Report",
  cancelReportConfirmation: "Are you sure you want to cancel this report? This action cannot be undone.",
  no: "No",
  yesCancel: "Yes, Cancel",
  cancel: "Cancel",
  sendReport: "Send Report",
  sending: "Sending...",
  additionalComments: "Additional Comments (Optional)",
  commentsPlaceholder: "Provide more details here...",
  selectReasonError: "Please select a reason for reporting.",
  descriptionLengthError: "Description cannot exceed 500 characters.",
  reportSentSuccess: "Report sent successfully! It will be reviewed shortly.",
  reportSendError: "Failed to send report. Please try again.",
  duplicateReportError: "You have already submitted this exact report.",
  selfReportError: "You cannot report yourself.",
  targetNotFoundError: "Book or user not found.",
  serverError: "Server error. Please try again later.",
  reportTitle: "Report Inappropriate Content",
  reportDescription: "Please select a reason and provide details below. Your feedback helps keep our community safe.",
  reasonForReporting: "Reason for Reporting",
  selectReason: "Select a reason",
  inappropriateContent: "Inappropriate Content",
  spamOrFake: "Spam or Fake",
  offensiveLanguage: "Offensive Language",
  harassment: "Harassment",
  scamOrFraud: "Scam or Fraud",
  other: "Other",
  invalidReportTarget: "Invalid report target.",
  suggest: "Suggest",
  suggestCategoryTitle: "Suggest a Category",
  suggestCategoryDescription: "Help us improve by suggesting a new book category",
  categoryName: "Category Name",
  categoryPlaceholder: "e.g., Science Fiction, History...",
  characters: "characters",
  requirements: "Requirements",
  atLeastThreeChars: "At least 3 characters",
  noNumbers: "No numbers allowed",
  maxFiftyChars: "Maximum 50 characters",
  submitting: "Submitting...",
  submitSuggestion: "Submit Suggestion",
  noNumbersError: "Category name cannot contain numbers",
  minCharactersError: "Category name must be at least 3 characters",
  maxCharactersError: "Category name must not exceed 50 characters",
  viewDetails: "View Details",
  confirmBookRemoval: "Confirm Book Removal",
  removeBookConfirmation: "Are you sure you want to remove this book from your wishlist? This action cannot be undone.",
  yesRemove: "Yes, Remove",
  clearWishlist: "Clear Wishlist",
  confirmClearWishlist: "Confirm Clear Wishlist",
  clearWishlistConfirmation: "Are you sure you want to remove all items from your wishlist? This action cannot be undone.",
  yesClear: "Yes, Clear",
  wishlistCleared: "Wishlist cleared successfully!",
  emptyWishlistTitle: "Your wishlist is empty",
  emptyWishlistSubtitle: "Add your favorite books and find them here later.",
  mySavedBooks: "My Saved Books",
  loadingWishlist: "Loading wishlist...",
  wishlist: "Wishlist",
  notification: "Notification",
  myProfile: "My Profile",
  logout: "Logout",
  language: "Language",
  noBookFound: "No book found.",
  selectDates: "Please select both start and end dates.",
  endDateAfterStart: "End date must be after start date.",
  requestSuccess: "Request sent successfully.",
  notAvailable: "N/A",
  free: "Free",
  perDay: "day",
  noDescription: "No description available.",
  selectBorrowDuration: "Select Borrow Duration:",
  startDate: "Start Date",
  endDate: "End Date",
  reservedDays: "Reserved days (not available)",
  confirmOperation: "Confirm Operation",
  confirmMessage: "Are you sure you want to complete this",
  confirm: "Confirm",
  operationSummary: "Operation Summary",
  reviewOrderDetails: "Please review your order details.",
  operation: "Operation",
  borrowDays: "Borrow days",
  days: "day(s)",
  pricePerDay: "Price per day",
  total: "Total",
  selectValidDates: "Select valid dates",
  process: "Process",
  buy: "Buy",
  borrow: "Borrow",
  donate: "Donate",
  toBorrow: "Borrow",
  toDonate: "Donate",
  editBookTitle: "Edit Your Book",
  onlyImagesAllowed: "Only image files are allowed",
  imageTooLarge: "Image must be less than 5MB",
  priceNegative: "Price cannot be negative",
  titleTooShort: "Title must be at least 2 characters",
  categoryRequired: "Category is required",
  descriptionTooShort: "Description must be at least 10 characters",
  priceRequired: "Price is required",
  pricePerDayRequired: "Price per day is required",
  priceMustBePositive: "Price must be greater than zero",
  pricePerDayMustBePositive: "Price per day must be greater than zero",
  updatingBook: "Updating your book...",
  bookUpdatedSuccess: "Book updated successfully!",
  redirectingProfile: "Redirecting to your profile...",
  updateBook: "Update Book",
  title: "Title",
  selectCategory: "Select category",
  price: "Price",
  pricePerDay: "Price Per Day",
  description: "Description",
  currentImage: "Current Image:",
  bookCoverAlt: "Book cover",
  newImage: "New Image",
  changeBookCoverOptional: "Change Book Cover (Optional)",
  bookCoverPreview: "Book cover preview",
  changeImage: "Change Image",
  changeBookCover: "Change Book Cover",
  uploadBookCover: "Upload Book Cover",
  chooseDifferentImage: "Click to choose a different image",
  keepCurrentImage: "Current image will be kept if you don't upload a new one",
  uploadImageHelp: "Upload an image (max 5MB)",
  invitations: "Invitations",
  notifications: "Notifications",
  noNotifications: "No notifications",
  accept: "Accept",
  refuse: "Refuse",
  invalidPaymentNotification: "Invalid payment notification.",
  paymentFailed: "Payment failed",
  paymentFailedTryAgain: "Payment failed. Please try again.",
  processing: "Processing...",
  payNow: "Pay Now",
  completePayment: "Complete Your Payment",
  close: "Close",
  noNotificationsYet: "No notifications yet",
  actionRequired: "ACTION REQUIRED",
  recentActivity: "Recent Activity",
  justNow: "just now",
  minutesAgo: "m ago",
  hoursAgo: "h ago",
  daysAgo: "d ago",
  request: "Request",
  writeReasonForRefusal: "Write the reason for refusal",
  sendRefusal: "Send Refusal",
  switchToArabic: "Switch to Arabic",
  switchToEnglish: "Switch to English",
};

export default en;
