const en = {
  //Book Details
  bookRemoved: 'Book removed from wishlist',
  bookAdded: 'Book added to wishlist',
  errorMessage: 'Something went wrong.',
  forSale: 'For Sale',
  currentlyBorrowed: 'Currently borrowed (you can reserve another period)',
  availableToBorrow: 'Available to Borrow',
  availableToExchange: 'Available to Exchange',
  freeToDonate: 'Free to Donate',
  bookNotFound: 'Book not found or unavailable.',
  general: 'General',
  proceedToOrder: 'Proceed to Order',
  reportBook: 'Report this book',
  by: 'by',
  unknownAuthor: 'Unknown Author',
  listedBy: 'Listed By:',
  unknown: 'Unknown',
  home: 'Home',
  category: 'Category',
  currency: 'EGP',
  noReportsFound: 'No Reports Found',
  noReportsDescription:
    "You haven't submitted any reports yet. Explore books and report any issues you find.",
  browseBooks: 'Browse Books',
  status: 'Status',
  targetType: 'Target Type',
  all: 'All',
  pending: 'Pending',
  reviewed: 'Reviewed',
  dismissed: 'Dismissed',
  cancelled: 'Cancelled',
  user: 'User',
  book: 'Book',
  mySubmittedReports: 'My Submitted Reports',
  showingResults: 'Showing {start} to {end} of {total} results',
  target: 'Target',
  reason: 'Reason',
  dateSubmitted: 'Date Submitted',
  action: 'Action',
  userNotFound: 'User Not Found',
  bookNotFound: 'Book Not Found',
  confirmCancelReport: 'Confirm Cancel Report',
  cancelReportConfirmation:
    'Are you sure you want to cancel this report? This action cannot be undone.',
  no: 'No',
  yesCancel: 'Yes, Cancel',
  cancel: 'Cancel',
  pending: 'Pending',
  reviewed: 'Reviewed',
  dismissed: 'Dismissed',
  cancelled: 'Cancelled',
  sendReport: 'Send Report',
  sending: 'Sending...',
  reportBook: 'Report Book',
  additionalComments: 'Additional Comments (Optional)',
  commentsPlaceholder: 'Provide more details here...',
  selectReasonError: 'Please select a reason for reporting.',
  descriptionLengthError: 'Description cannot exceed 500 characters.',
  reportSentSuccess: 'Report sent successfully! It will be reviewed shortly.',
  reportSendError: 'Failed to send report. Please try again.',
  duplicateReportError: 'You have already submitted this exact report.',
  selfReportError: 'You cannot report yourself.',
  targetNotFoundError: 'Book or user not found.',
  serverError: 'Server error. Please try again later.',
  reportTitle: 'Report Inappropriate Content',
  reportDescription:
    'Please select a reason and provide details below. Your feedback helps keep our community safe.',
  reasonForReporting: 'Reason for Reporting',
  selectReason: 'Select a reason',
  inappropriateContent: 'Inappropriate Content',
  spamOrFake: 'Spam or Fake',
  offensiveLanguage: 'Offensive Language',
  harassment: 'Harassment',
  scamOrFraud: 'Scam or Fraud',
  other: 'Other',
  reportUser: 'Report User',
  invalidReportTarget: 'Invalid report target.',
  suggest: 'Suggest',
  suggestCategoryTitle: 'Suggest a Category',
  suggestCategoryDescription: 'Help us improve by suggesting a new book category',
  categoryName: 'Category Name',
  categoryPlaceholder: 'e.g., Science Fiction, History...',
  characters: 'characters',
  requirements: 'Requirements',
  atLeastThreeChars: 'At least 3 characters',
  noNumbers: 'No numbers allowed',
  maxFiftyChars: 'Maximum 50 characters',
  submitting: 'Submitting...',
  submitSuggestion: 'Submit Suggestion',
  noNumbersError: 'Category name cannot contain numbers',
  minCharactersError: 'Category name must be at least 3 characters',
  maxCharactersError: 'Category name must not exceed 50 characters',
  viewDetails: 'View Details',
  confirmBookRemoval: 'Confirm Book Removal',
  removeBookConfirmation:
    'Are you sure you want to remove this book from your wishlist? This action cannot be undone.',
  yesRemove: 'Yes, Remove',
  remove: 'Remove',
  clearWishlist: 'Clear Wishlist',
  confirmClearWishlist: 'Confirm Clear Wishlist',
  clearWishlistConfirmation:
    'Are you sure you want to remove all items from your wishlist? This action cannot be undone.',
  yesClear: 'Yes, Clear',
  wishlistCleared: 'Wishlist cleared successfully!',
  emptyWishlistTitle: 'Your wishlist is empty',
  emptyWishlistSubtitle: 'Add your favorite books and find them here later.',
  mySavedBooks: 'My Saved Books',
  loadingWishlist: 'Loading wishlist...',
  home: 'Home',
  addBook: 'Add Book',
  wishlist: 'Wishlist',
  notification: 'Notification',
  myProfile: 'My Profile',
  logout: 'Logout',
  language: 'Language',

   profile: {
    // Profile Header
    myReports: "My Reports",
    changeProfilePicture: "Change profile picture",
    memberSince: "Member since",
    
    // Tab Navigation
    myBooks: "My Books",
    userBooks: "User's Books",
    
    // Books Grid
    noBooksFound: "No books found",
    noBooksDescription: "No books available to display at the moment",
    
    // Book Card
    forSale: "For Sale",
    forBorrow: "For Borrow",
    forExchange: "For Exchange", 
    forDonation: "For Donation",
    pendingOrder: "Pending Order",
    editBook: "Edit Book",
    deleteBook: "Delete Book",
    confirmDelete: "Confirm Delete",
    deleteConfirmation: "Are you sure you want to delete this book?",
    cancel: "Cancel",
    delete: "Delete",
    
    // Public Profile
    reportUser: "Report User",
    friends: "Friends",
    
    // Loading States
    loadingProfile: "Loading profile...",
    loadingBooks: "Loading books...",
    
    // Error States
    errorLoadingProfile: "Error loading profile",
    errorLoadingBooks: "Error loading books",
    retry: "Retry"
  }
};

export default en;
